version = 1
SPDX-PackageName = "Sandwich Station"
SPDX-PackageSupplier = "SandwichStation <sandwichstation@b3ckdoor.com>"
SPDX-PackageDownloadLocation = "https://sandwichstation.b3ckdoor.com"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"
