- type: job
  id: offduty
  name: job-name-offduty
  description: job-description-offduty
  playTimeTracker: JobOffDuty
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # 2 hrs overall playtime
  startingGear: offdutyGear
  icon: "JobIconoffduty"
  supervisors: job-supervisors-everyone
  goobcoins: 0 # Off-duty, so your not earning anything
  access:
   - Maintenance # Unlike passengers, you earned your access

- type: startingGear
  id: offdutyGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
